### ISSUE TITLE
Update travis.yml in all Kitura repos to leverage script_travis.sh.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura-Build#11]
Let's use a PR for all of these updates.

**Comment by rolivieri** [comment]
See this Wiki page for a list of all the Kitura repos: https://github.com/IBM-Swift/Kitura/wiki/Kitura-repositories

**Comment by ianpartridge** [comment]
Please keep @youming-lin involved in this, he's taking over Kitura Travis ownership from @dfirsht

**Comment by rolivieri** [comment]
@ianpartridge Sounds good, sure. @youming-lin @BDHernand will be creating several PRs as part of a refactoring effort. When he submits these PRs, please review them and let us know if you have any questions.

**Comment by BDHernand** [comment]
Created Pull requests for all Repo's that have an existing .travis.yml file where it was appropriate.  Kitura-Redis is failing to build.

**Comment by BDHernand** [comment]
Kitura-redis now has a PR on it.  Waiting for the PR's to be merged before closing this issue
