### ISSUE TITLE
Use a different repo name (coordinate with Kitura team).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura-Build#15]
Since this repo is now used for several other Swift packages (not only Kitura packages), we will use a different name for the repo: `Package-Builder`.

To accomplish this task and not break all the different repos, we may need to keep this repo for a little bit and create a new one with the new name. Once we finish migrating all repos to use the new one, then we can just remove this one and keep the new one. We will coordinate with Kitura team before any work related to this task is done.

**Comment by BDHernand** [comment]
Getting a weird travis CI failure.  Have an email out to travis support on it to see what is going on.  The travsi CI repo for IBM-Swift/Kitura-CouchDB is failing with my changes.  I have reviewed the changes and so has Ian and we cant find anything wrong.  Waiting on the email to shed some light
