### ISSUE TITLE
Add logic to parse .swift-version file.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura-Build#2]
Update the `build_kitura_package.sh` file accordingly:
1) If the repo has a .swift_version file, then use the value in that file as the version.
2) Otherwise, use the swift_version hardcoded in the `build_kitura_package.sh`.

**Comment by dfirsht** [comment]
To maintain consistency with https://github.com/kylef/swiftenv, it should look for a `.swift-version` file.

**Comment by BDHernand** [comment]
This has been completed in the master branch
